### ISSUE TITLE
How to send notifications to client?

### ISSUE THREAD

**Issue by flight643** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#10]
Can you give an example please?

**Comment by baudev** [comment]
To send a notification to the client, you must specify the notification payload using `$message->setNotification();`. See [Notification payload](https://firebase.google.com/docs/cloud-messaging/xmpp-server-ref#notification-payload-support) for more details.

Here is a basic example:
```php
$message = new \FCMStream\Message();
$message->setTo($from);
$message->setMessageId("message_id_test");
$message->setPriority(\FCMStream\Message::PRIORITY_HIGH);
$message->setNotification(array("title" => "Here the title", "body" => "This is the body test!"));
$actions->sendMessage($message);
```

Indeed, for a future release it would be easier and useful creating `iOSNotificationPayload` and `AndroidNotificationPayload` objects.

**Comment by flight643** [comment]
@baudev Thanks for the answer! I have tried to create message that way before opening this issue but facing with error:
`'fwrite() expects parameter 1 to be resource, null given' in /www/code/vendor/baudev/fcm-xmpp/src/Core.php:295`

My code is:
```php
        $fcmXmpp = new FcmXmpp(<someSenderId>,<someApiKey>, '/test.txt');
        $actions = new Actions($fcmXmpp);

        $message = new Message();
        $message->setTo(<someFcmToken>);
        $message->setMessageId('test_message_id');
        $message->setNotification(['title' => 'test', 'body' => 'test']);
        $message->setPriority(Message::PRIORITY_HIGH);
        $actions->sendMessage($message);
```

Where FcmXmpp is the class that extends Core class.

**Comment by baudev** [comment]
Doing that will not work as the connection has not been established. With some modifications the code can work. However, I must admit that in its current state, this framework was not designed to send messages but rather to respond to received messages. In the coming days, a solution will be found to allow this: https://github.com/baudev/Firebase-Cloud-Messaging-FCM-XMPP/pull/8 (This PR is only a few days old and expresses the same need).

I'd be interested to know your need if it's not intrusive.
If the framework offered you to send notifications only every x seconds, would that be okay with you?

I would also like to draw your attention to the fact that XMPP communication is not necessarily the one that meets your needs. Indeed, if you have to send notifications only rarely and/or not almost instantaneously, then an HTTP request will be more appropriate. Indeed, an XMPP connection requires the establishment of a connection that can take up to 1 second. If you need to open a connection for one or two notifications, there is no point in using this protocol.

**Comment by flight643** [comment]
My need is to send push notifications to thousands clients and get receipt when push has been delivered. So i've interested in sending notifications as fast as possible and HTTP request not suitable for me due to lack of delivery confirmation. Anyway big thanks for answering. 
In any case, thank you very much for your reply.

**Comment by baudev** [comment]
Indeed, in this case the XMPP protocol is well adapted. The solution proposed for the next version is explained here #11. What do you think of that?

**Comment by baudev** [comment]
@flight643

**Comment by baudev** [comment]
It can be done now in the [`v1.0.0`](https://github.com/baudev/Firebase-Cloud-Messaging-FCM-XMPP/releases/tag/v1.1.0) :tada:
