### ISSUE TITLE
What's happen when server script is down ?

### ISSUE THREAD

**Issue by Lecraver** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#12]
Hi,
I use your program successfully. 
A question: if the script falls, it does not recover all messages received by FCM when it is restarted ! Is there a solution ?
Thank you for your work,

**Comment by baudev** [comment]
I didn't make tests concerning this case. 

Have your messages a `time_to_live` parameter set? [More information about it.](https://firebase.google.com/docs/cloud-messaging/concept-options#ttl).

**Comment by Lecraver** [comment]
Apologies, it works but it takes time when restarting the script. it takes 3 minutes !

Script launch -> message received
2019-07-01T12:23:47 -> 2019-07-01T12:26:38
2019-07-01T12:36:19 -> 2019-07-01T12:39:27

**Comment by baudev** [comment]
It takes 3 minutes to receive the messages that were sent while the script was down? Or even the messages sent while the script was launched again?

Can you try the following steps:
- Launch the script
- Send message (we will call it `message_1`)
- Exit the script
- Send message (we will call it `message_2`)
- Launch again the script
- Send message (we will call it `message_3`).

For each message, give the sending time and reception time please (and also the datetime of the other steps).

**Comment by Lecraver** [comment]
message_1 -> received instantly 
message_2 -> received 3 minutes after restarting script
message_3 -> received instantly

script launch at **2019-07-04 09:33:15**
message_1 send at **2019-07-04 11:11:33**
message_1 received at **2019-07-04 11:11:35**
script stop
message_2 send at **2019-07-04 11:11:55**
script launch at **2019-07-04 11:12:02**
message_2 received at **2019-07-04 11:14:57**
message_3 send at **2019-07-04 11:15:23**
message_3 received at **2019-07-04 11:15:24**

**Comment by baudev** [comment]
Thanks.

I will investigate on it but it's probably due to Firebase service. Your messages are perhaps queued into an important stack (due to the large amount of Firebase users).

**Comment by Lecraver** [comment]
Ok, thank you for answering me and for your work !
