### ISSUE TITLE
Will this suite my use?

### ISSUE THREAD

**Issue by raymiec** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#13]
I need to send notification to client devices when new orders are received. Currently using FCM over HTTP.  I need confirmations on delivery and respond if delivery fails with x amount of time, say if it ain't delivered within 5 minutes do X.

I don't want to mess too much with existing code on my server for now, with this library could i just run it in the background with something like nohup, and deal with failures there, with the current http sending method on my server just add the delivery receipts flag? or does the data payload have to be sent with the library?

**Comment by baudev** [comment]
This library can be adapted to your needs if the `x amount of time` is a very short time frame. XMPP is especially useful for sending instant messages.

The `delivery_receipt_requested` option is supported by version `1.0.2` of this library and will be released soon. However, this Firebase option is only supported for Android devices (source: https://firebase.google.com/docs/cloud-messaging/xmpp-server-ref). 
Nevertheless, it is possible on iOS to manually send an upstream message to confirm the notification has been received.

I advise you for simplicity to choose between HTTP and XMPP and not to use both.

**Comment by baudev** [comment]
The `delivery_receipt_requested` option is now available in  [`v1.0.0`](https://github.com/baudev/Firebase-Cloud-Messaging-FCM-XMPP/releases/tag/v1.1.0).

I close for inactivity.
