### ISSUE TITLE
About server and database

### ISSUE THREAD

**Issue by BlueAnthony** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#14]
Do you mean after I install your fcm-xmpp, my computer will run as a server and also as a database?
In my case, I have two phones and one laptop.
I want mobile phone A to upstream the message to the laptop, then mobile phone B will downstream the message from the laptop.
Should I set another device as database?
Thank you!

**Comment by baudev** [comment]
As explained in the diagrams here, your computer will indeed act as a server between the two phones. 

- **Downstream Messages:** server-to-device through FCM
![image](https://user-images.githubusercontent.com/29781702/62282332-a549bd00-b44f-11e9-8d49-0886220ab2fd.png)

- **Upstream Messages:** device-to-server through FCM
![image](https://user-images.githubusercontent.com/29781702/62282484-f35ec080-b44f-11e9-8de8-97c66724a20b.png)

The database on diagrams represents Google's database that stores messages while waiting to be delivered to the recipient.

This project only allows to retrieve upstream messages and send downstream messages. Then, depending on your needs, you can add a database to your project.
