### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by BlueAnthony** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#15]
![image](https://user-images.githubusercontent.com/17959032/62194488-880fe280-b3ac-11e9-9df6-08e29daa8319.png)
As image above, I can't install the package.
My environment is: 
PHP version: 7.0-cli
Ubuntu version: 16.04

Any suggestion?
Thank you!!

**Comment by baudev** [comment]
This repository requires PHP `7. 2` or higher version. 
I will add it into the `README`.

**Comment by BlueAnthony** [comment]
![image](https://user-images.githubusercontent.com/17959032/62260586-0c15a900-b445-11e9-9f4f-4914800c7ace.png)
Hi, baudev. I change to php 7.2, but I have another problem.
Should I install "sebastian/version"?

**Comment by baudev** [comment]
This repository doesn't require any dependency. 

Your screen shows that you have declared other dependencies into your `composer.json`. This error is consequently not linked to this project.

--- 

The installation of this project is normally easy.

- Create a new directory
- Type `composer require baudev/fcm-xmpp`

:tada:
