### ISSUE TITLE
110 Connection timed out

### ISSUE THREAD

**Issue by Lecraver** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#16]
Hello,

I have a problem. The script works well on my local machine with PHP 7.3.7 but I get a timeout on my server with PHP 7.3.9. 
Here is the error:

`=== Connecting to fcm-xmpp.googleapis.com:5235 at 2019-09-05T15:58:17+0000 === 2019-09-05T15:58:17+0000 ===
PHP Warning:  stream_socket_client(): unable to connect to tls://fcm-xmpp.googleapis.com:5235 (Connection timed out) in /var/www/vhosts/xxxx.com/httpdocs/api-test/vendor/baudev/fcm-xmpp/src/Core.php on line 118
`

Do you think it's a PHP problem or a configuration problem at firebase?

Many thanks,

Best regards,

**Comment by caveman99** [comment]
Could be firewall, old OpenSSL Version on the server or a shared hoster preventing outbound connects.

**Comment by Lecraver** [comment]
We have a dedicated server freshly installed with Debian 9.
```
openssl version 
OpenSSL 1.1.0k  28 May 2019
```
The server is not shared with anyone it's a dedicated server

How can I check if the port is blocked by a firewall?

Many thanks,
