### ISSUE TITLE
Script randomly get stuck in an infinite loop

### ISSUE THREAD

**Issue by kungufli** [baudev/Firebase-Cloud-Messaging-FCM-XMPP#5]
Recently my script got stuck in a loop, printing out to log many rows like this:

`=== Read 0 bytes === {{timestamp}} ===`

When it happens the script don't receive FCM messages from the Google server anymore and the log get flooded with these `Read 0 bytes` messages at a rate of hundreds per seconds, like it got stuck in a loop. The only way to recover is to kill the process and restart. 

I started seeing this behavior in the 1.0.1 version, so I suspect that some change related to another [recent issue](https://github.com/baudev/Firebase-Cloud-Messaging-FCM-XMPP/issues/2) could be involved. I run this server for months and never seen that in 1.0.0, but already happened three times in the last week with 1.0.1.

**Comment by baudev** [comment]
Can you send the log rows just before the first occurrence of  `=== Read 0 bytes === {{timestamp}} ===` please?

**Comment by kungufli** [comment]
Sure, I didn't attached that in the original post because it looks like there isn't anything interesting to me:

`=== Read 549 bytes === 2019-04-29T20:08:48+0200 ===`
`<message to="xxxxxxxxxxxx@gcm.googleapis.com" from="devices@gcm.googleapis.com" type="normal"><gcm xmlns="google:mobile:data">{"data":{"t":"l","device_id":"xxxxxxxxxxxxxxx","latitude":"xx.xxxxxxx","accuracy":"110.0","time":"1556561327832","battery":"6-","longitude":"xx.xxxxxxx"},"time_to_live":86400,"from":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","message_id":"L15565613280141","category":"xxxxxxxxxxxxxxxxxxxxxxxxx"}</gcm></message>`
`=== Message is not fragmented. === 2019-04-29T20:08:48+0200 ===`
`=== Sent 277 bytes === 2019-04-29T20:08:48+0200 ===`
`<message id=""><gcm xmlns="google:mobile:data">{"to":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","message_id":"L15565613280141","message_type":"ack"}</gcm></message>`
`=== Read 552 bytes === 2019-04-29T20:08:49+0200 ===`
`<message to="xxxxxxxxxxxx@gcm.googleapis.com" from="devices@gcm.googleapis.com" type="normal"><gcm xmlns="google:mobile:data">{"data":{"t":"l","device_id":"xxxxxxxxxxxxxxx","latitude":"xx.xxxxxxx","accuracy":"23.976","time":"1556561334228","battery":"69-","longitude":"xx.xxxxxxx"},"time_to_live":86400,"from":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","message_id":"L15565613343051","category":"xxxxxxxxxxxxxxxxxxxxxxxxx"}</gcm></message>`
`=== Message is not fragmented. === 2019-04-29T20:08:49+0200 ===`
`=== Sent 277 bytes === 2019-04-29T20:08:49+0200 ===`
`<message id=""><gcm xmlns="google:mobile:data">{"to":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","message_id":"L15565613343051","message_type":"ack"}</gcm></message>`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`
`=== Read 0 bytes === 2019-04-29T20:08:52+0200 ===`

**Comment by baudev** [comment]
Thanks. I will work on it as soon I can.

**Comment by baudev** [comment]
As explained in the above PR, the last version `v1.0.1` was responsible of not sending `Keep Alive` message anymore.
It is now fixed and patched in `v1.0.1` :tada:

**Comment by kungufli** [comment]
Awesome! Many thanks!

**Comment by kungufli** [comment]
@baudev Sorry to bother you, but I noticed that after the fix the script now send a `Keepalive exchange` on each message received (while on v1.0.0 it was only happening once in a while), is that correct/safe?

**Comment by baudev** [comment]
Indeed, I had not noticed this behaviour. Although this is not a problem, it does not remain desired.

**Comment by baudev** [comment]
The `v1.0.1` has been updated to remove this bug. 
Thanks again for having reported it.

**Comment by kungufli** [comment]
Hi, recently I started a new project using version `v1.1.0` and unfortunately I'm seeing this behavior again, a lot of these messages:

`=== Read character 32 === 2022-12-16T17:12:48+0100 ===`
`=== Keepalive exchange === 2022-12-16T17:12:48+0100 ===`
`=== Sent 2 bytes === 2022-12-16T17:12:48+0100 ===`
`=== Read character 32 === 2022-12-16T17:17:53+0100 ===`
`=== Keepalive exchange === 2022-12-16T17:17:53+0100 ===`
`=== Sent 2 bytes === 2022-12-16T17:17:53+0100 ===`
`=== Read character 32 === 2022-12-16T17:22:54+0100 ===`
`=== Keepalive exchange === 2022-12-16T17:22:54+0100 ===`
`=== Sent 2 bytes === 2022-12-16T17:22:54+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:23:33+0100 ===`

and a few millions (really, something like 3 millions) rows later:

`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Read 0 bytes === 2022-12-16T17:24:33+0100 ===`
`=== Keepalive exchange === 2022-12-16T17:24:34+0100 ===`
`=== Reconnecting to the FCM Server in 10 seconds.  === 2022-12-16T17:24:34+0100 ===`
`=== Connecting to fcm-xmpp.googleapis.com:5235 at 2022-12-16T17:24:44+0100 === 2022-12-16T17:24:44+0100 ===`
`=== Sent 124 bytes === 2022-12-16T17:24:44+0100 ===`
`<stream:stream to="gcm.googleapis.com" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">`
`=== Read 147 bytes === 2022-12-16T17:24:44+0100 ===`

As you can see, the bug seems to start randomly and it's not triggered by a incoming message. It eventually recover, after some minutes, on the next `Keepalive exchange`, as it seems, but that's sufficient to rapidly flood the log with GBs of data, making it really difficult to analyze. Moreover, during the time it's stuck, the server is unable to correctly receive incoming messages.

My other project (on which I firstly encountered this bug) is still running fine, from years now, on version `v1.0.1` and it's not experiencing this issue.
